### PR TITLE
Revised pom.xml to solve dependency issues

### PR DESCRIPTION
**Pull request by yy20716**
Hello, it seems that specifying top versions at pom.xml rather causes the issue. I confirmed that this revision allows passing all tests and checking dependencies of packages without causing issues when I ran maven (i.e. mvn clean install). Thank you.

### CODE REVIEW

**Comment by pnrobinson** [comment]
Thanks so much @yy20716 !

On my system, I not getting any further enforcer errors, but I am getting this
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.805 s <<< FAILURE! - in com.github.phenomics.ontolib.io.owl.OwlImmutableOntologyLoaderTest
[ERROR] testLoader(com.github.phenomics.ontolib.io.owl.OwlImmutableOntologyLoaderTest)  Time elapsed: 0.752 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at com.github.phenomics.ontolib.io.owl.OwlImmutableOntologyLoaderTest.testLoader(OwlImmutableOntologyLoaderTest.java:29)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
	at com.github.phenomics.ontolib.io.owl.OwlImmutableOntologyLoaderTest.testLoader(OwlImmutableOntologyLoaderTest.java:29)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   OwlImmutableOntologyLoaderTest.testLoader:29 » NoClassDefFound com/fasterxml/j...

```
I have not been able to figure out where this is coming from--any ideas?

**Comment by yy20716** [comment]
I am so sorry. The problem is that I cannot reproduce your error on my machine and other linux machines. Could you please remove your maven local repo directory (i.e. ${user.home}/.m2 ) and retry one more time?

**Comment by pnrobinson** [comment]
Just tried this on my home box (ubuntu machine) and everything builds with no errors. So tomorrow I will take your advise and do a fresh checkout and delete the .m2 if necessary. Thanks for the work on this!

**Comment by pnrobinson** [comment]
It is now working on all machines, thanks!

**Pull request merged**
